# Generated by Django 3.1.1 on 2020-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.CharField(choices=[('free', 'free'), ('unfree', 'unfree')], default='-', max_length=50)),
                ('category', models.CharField(choices=[('backend', 'backend'), ('frontend', 'frontend'), ('fullstack', 'fullstack'), ('waiting', 'waiting')], default='-', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('seats_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('borrowed_from', models.DateTimeField(blank=True, null=True)),
                ('borrowed_to', models.DateTimeField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=30000, null=True)),
                ('borrowed_rooms', models.ForeignKey(blank=True, null=True, on_delete=models.SET(1), related_name='users', to='office_api.officeroom')),
            ],
        ),
    ]
